### PR TITLE
feat(bottender-facebook): implement isPostReaction

### PR DESCRIPTION
**Pull request by wtflink**
With isReactionOnPost, we can easily tell whether the post or the comment that the reaction given to.

### CODE REVIEW

**Comment by tw0517tw** [comment]
maybe we can also add a `isReactionOnComment` ?

**Comment by wtflink** [comment]
Actually, we can categorize reaction events into reactionOnComment/reactionOnFirstLayerComment/reactionOnSecondLayerComment
but the naming is quite tricky, so in this pull request I skip those reaction on comment events, to make thing simple

**Comment by chentsulin** [comment]
We now have another event called `isPageLike`, so should it be renamed to `isLikeOnPage`?

1. first group

- isPageLike
- isPostReaction
- isCommentReaction
- isFirstLayerCommentReaction
- isSecondLayerCommentReaction

2. second group

- isLikeOnPage
- isReactionOnPost
- isReactionOnComment
- isReactionOnFirstLayerComment
- isReactionOnSecondLayerComment

Which one is better?

**Comment by wtflink** [comment]
I would go with 2, makes more sense when things get complicated

**Comment by chentsulin** [comment]
I'd like to adopt `isPostReaction`, so we don't need to rename a lot of other fields.

**Pull request merged**
