### PR TITLE
docs: implement new website

### PR DESCRIPTION
**Pull request by jigsawye**
Implement new website with Docusaurus

Preview: 

screencapture-localhost-3001-2019-09-24-17_51_48

### CODE REVIEW

**Comment by jigsawye** [comment]
@chentsulin please fill out the content of landing page

**Comment by chentsulin** [comment]
To start the website server:

```
cd website && yarn && yarn start
```

**Comment by chentsulin** [comment]
image

**Comment by chentsulin** [comment]
We can have multiple versions docs now: 

螢幕快照 2019-10-08 下午6 02 36

**Comment by chentsulin** [comment]
It still have some styling issues, but I think it can be merged for now.

image

**Pull request merged**
